name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: yarn install
        run: |
          rm -rf node_modules && yarn install --frozen-lockfile
      - name: deploy
        run: |
          zip -r deploy.zip ./* -x ./vercel/* ./.github/*
          aws lambda update-function-code --function-name=leetcode-stats --zip-file=fileb://deploy.zip
